import type { BriefContent } from '../../hooks/useBrief';
import GlassCard from '../shared/GlassCard';

interface PlainLanguageSummaryProps {
  brief: BriefContent | null;
}

export default function PlainLanguageSummary({ brief }: PlainLanguageSummaryProps) {
  return (
    <GlassCard style={{ position: 'relative', overflow: 'hidden' }}>
      {/* Top gradient line */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height: 2,
          background: 'linear-gradient(90deg, var(--accent-blue), var(--accent-violet))',
        }}
      />

      <div style={{ paddingTop: 8 }}>
        {/* AI Verdict label */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
          <span style={{ fontSize: 18 }}>✨</span>
          <span
            style={{
              fontSize: 14,
              fontWeight: 600,
              background: 'linear-gradient(135deg, var(--accent-blue), var(--accent-violet))',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            AI Verdict
          </span>
        </div>

        {/* Executive summary */}
        {brief?.executive_summary && (
          <p style={{ fontSize: 18, fontWeight: 300, color: 'var(--text-primary)', lineHeight: 1.7, marginBottom: 20 }}>
            {brief.executive_summary}
          </p>
        )}

        {/* Plain language verdict */}
        {brief?.plain_language_verdict && (
          <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
            {brief.plain_language_verdict}
          </p>
        )}

        {/* Attribution */}
        <div style={{ marginTop: 24, fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic' }}>
          Generated by Quantnance AI
        </div>
      </div>
    </GlassCard>
  );
}
